---
- name: Install node and npm
  hosts:  138.68.98.23
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      
    - name: Install nodejs and npm
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm

- name: Create1 new Linux user for nodejs app
  hosts: 138.68.98.23
  tasks:
    - name: Create node user
      ansible.builtin.user:
        name: node
        comment: node admin user
        group: admin  

- name: Deploy nodejs app
  hosts:  138.68.98.23
  become: True
  become_user: "{{ remote_user }}"
  vars_files:
    - project-vars.yaml
  vars:
    - remote_destionation: /home/"{{ remote_user }}"
  tasks:
    - name: Unpack the nodejs file
      ansible.builtin.unarchive:
        src: "developing-with-docker-{{ version }}.tgz"
        dest: "{{ remote_destination }}"

    - name: Install dependencies
      community.general.npm:
        path: "{{ remote_destination }}/package"

    - name: Start the application
      ansible.builtin.command:
        chdir: "{{ remote_destination }}/package"
        cmd: node server
      #make the task asynchronous
      async: 1000
      poll: 0

    - name: Ensure app is running
      ansible.builtin.shell: ps aux | grep node
      register: app_status

    - name: Output the app-status
      ansible.builtin.debug:
        msg: "The app status is {{ app_status }}"
