pipeline{
    agent any
    stages{
        stage("copy files to ansible server"){
            steps{
                script{
                    echo "Copying necessary files to the ansible controller"
                    sshagent(['ansible-controller-key']){
                        sh "scp -o StrictHostKeyChecking=no ansible-jenkins/ansible/* root@64.227.124.93:/root"

                        withCredentials([
                            sshUserPrivateKey(credentialsId: 'ec2-instances-key', keyFileVariable: 'keyFile', usernameVariable: 'user')
                        ]){
                            sh 'scp $keyFile root@64.227.124.93:/root/ssh-key.pem'
                        }
                    }
                }
            }
        }
    }
}