pipeline{
    agent any
    environment {
        ANSIBLE_CONTROLLER_IP = "64.227.124.93"
    }
    stages{
        stage("copy files to ansible server"){
            steps{
                script{
                    echo "Copying necessary files to the ansible controller"
                    sshagent(['ansible-controller-key']){
                        sh "scp -o StrictHostKeyChecking=no ansible-jenkins/ansible/* root@${ANSIBLE_CONTROLLER_IP}:/root"

                        withCredentials([
                            sshUserPrivateKey(credentialsId: 'ec2-instances-key', keyFileVariable: 'keyFile', usernameVariable: 'user')
                        ]){
                            sh 'scp $keyFile root@$ANSIBLE_CONTROLLER_IP:/root/ssh-key.pem'
                        }
                    }
                }
            }
        }
        
        stage("Configure ec2 instances"){
            steps{
                script{
                    echo "configuring ec2 instances"
                    //define empty key-value pair object
                    def remote = [:]
                    remote.name = "ansible-controller"
                    remote.host = ANSIBLE_CONTROLLER_IP
                    remote.allowAnyHosts = true

                    withCredentials([
                        sshUserPrivateKey(credentialsId: 'ansible-controller-key', keyFileVariable: 'keyFile', usernameVariable: 'user')
                    ]){
                        remote.user = user
                        remote.identityFile = keyFile
                        sshScript remote: remote, script: "ansible-jenkins/prepare-ansible-conroller.sh"
                        sshCommand remote: remote, command: "ansible-playbook my-playbook.yaml"
                    }
                }
            }
        }
    }
}